services:
  frontend:
    build:
      context: ./frontend
    container_name: dailyworker-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    container_name: dailyworker-backend
    ports:
      - "9400:9400"
    volumes:
      - sqlite_data:/app/roster_data
    environment:
      - DB_PATH=roster_data/roster.db

volumes:
  frontend_node_modules:
  sqlite_data:
